PowerOfGod.Web/Controllers/ItemsController.cs
using PowerOfGod.Business.ShoppingLogic;
using PowerOfGod.Domain.Context;
using PowerOfGod.Domain.Entity.Shopping;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PowerOfGod.Web.Controllers
{
    public class ItemsController : Controller
    {
        private ApplicationDbContext db;
        private Item_Service item;
        Category_Service category_Service;
        public string shoppingCartID { get; set; }
        public const string CartSessionKey = "CartId";
        public ItemsController()
        {
            this.db = new ApplicationDbContext();
            this.item = new Item_Service();
            this.category_Service = new Category_Service();
        }
        public ActionResult Index()
        {
            return View(item.allItems());
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
                return RedirectToAction("Bad_Request", "Error");
            if (item.findItem_by_id(id) != null)
                return View(item.findItem_by_id(id));
            else
                return RedirectToAction("Not_Found", "Error");
        }
        public ActionResult Create()
        {
            ViewBag.Category_ID = new SelectList(category_Service.allCategories(), "Category_ID", "Name");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Item model, HttpPostedFileBase img_upload)
        {
            //var itm = db.Items.Where(x=>x.QuantityInStock==model.QuantityInStock);
            ViewBag.Category_ID = new SelectList(category_Service.allCategories(), "Category_ID", "Name");
            byte[] data = null;
            data = new byte[img_upload.ContentLength];
            img_upload.InputStream.Read(data, 0, img_upload.ContentLength);
            model.Picture = data;
            // itm= model.QuantityInStock  ;
            if (ModelState.IsValid)
            {
                item.addItem(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public ActionResult Edit(int? id)
        {
            ViewBag.Category_ID = new SelectList(category_Service.allCategories(), "Category_ID", "Name");
            if (id == null)
                return RedirectToAction("Bad_Request", "Error");
            if (item.findItem_by_id(id) != null)
                return View(item.findItem_by_id(id));
            else
                return RedirectToAction("Not_Found", "Error");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Item model, HttpPostedFileBase img_upload)
        {
            byte[] data = null;
            data = new byte[img_upload.ContentLength];
            img_upload.InputStream.Read(data, 0, img_upload.ContentLength);
            model.Picture = data;
            if (ModelState.IsValid)
            {
                item.editItem(model);
                return RedirectToAction("Index");
            }
            ViewBag.Category_ID = new SelectList(category_Service.allCategories(), "Category_ID", "Name");
            return View(model);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return RedirectToAction("Bad_Request", "Error");
            if (item.findItem_by_id(id) != null)
                return View(item.findItem_by_id(id));
            else
                return RedirectToAction("Not_Found", "Error");
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            item.deleteItem(item.findItem_by_id(id));
            return RedirectToAction("Index");
        }


        public ActionResult Fall_catalog()
        {
            return View(item.allItems());
        }
       
        public string GetCartID()
        {
            if (System.Web.HttpContext.Current.Session[CartSessionKey] == null)
            {
                if (!String.IsNullOrWhiteSpace(System.Web.HttpContext.Current.User.Identity.Name))
                {
                    System.Web.HttpContext.Current.Session[CartSessionKey] = System.Web.HttpContext.Current.User.Identity.Name;
                }
                else
                {
                    Guid temp_cart_ID = Guid.NewGuid();
                    System.Web.HttpContext.Current.Session[CartSessionKey] = temp_cart_ID.ToString();
                }
            }
            return System.Web.HttpContext.Current.Session[CartSessionKey].ToString();
        }
    }
}

PowerOfGod.Web/Controllers/ShoppingController.cs
using Microsoft.Ajax.Utilities;
using PowerOfGod.Business.ShoppingLogic;
using PowerOfGod.Domain.Context;
using PowerOfGod.Domain.Entity.Memberss;
using PowerOfGod.Domain.Entity.Shopping;
using SendGrid;
using SendGrid.Helpers.Mail;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace PowerOfGod.Web.Controllers
{
    public class ShoppingController : Controller
    {
        private Cart_Service cart_Service;
        private Item_Service item_Service;
        private Customer_Service customer_Service;
        private Order_Service order_Service;
        private Affiliate_Service affiliate_Service;
        private Department_Service department_Service;
        private Address_Service address_Service;

        private ApplicationDbContext db = new ApplicationDbContext();
        public string shoppingCartID { get; set; }
        public const string CartSessionKey = "CartId";

        public ShoppingController()
        {
            this.cart_Service = new Cart_Service();
            this.item_Service = new Item_Service();
            this.customer_Service = new Customer_Service();
            this.order_Service = new Order_Service();
            this.affiliate_Service = new Affiliate_Service();
            this.department_Service = new Department_Service();
            this.address_Service = new Address_Service();
        }
        public ActionResult Index(int? id)
        {
            var items_results = new List<Item>();
            try
            {
                if(id!=null)
                {
                    if(id==0)
                    {
                        items_results = item_Service.allItems();
                        ViewBag.Department = "All Departments";
                    }
                    else
                    {
                        items_results = item_Service.allItems().Where(x => x.Category.Department_ID == (int)id).ToList();
                        ViewBag.Department = department_Service.findDepartment_by_id(id).Department_Name;
                    }                    
                }
                else
                {
                    items_results = item_Service.allItems();
                    ViewBag.Department = "All Departments";
                }
            }
            catch(Exception ex) { }
            return View(items_results);
        }
        public ActionResult add_to_cart(int id)
        {
            var item = item_Service.findItem_by_id(id);
            if (item != null)
            {
                cart_Service.add_item_to_cart(id);
                return RedirectToAction("Index");
            }
            else
                return RedirectToAction("Not_Found", "Error");
        }
        public ActionResult remove_from_cart(string id)
        {
            var item = cart_Service.get_Cart_Items().FirstOrDefault(x => x.cart_item_id == id);
            if (item != null)
            {
                cart_Service.remove_item_from_cart(id: id);
                return RedirectToAction("ShoppingCart");
            }
            else
                return RedirectToAction("Not_Found", "Error");
        }
        public ActionResult ShoppingCart()
        {
            ViewBag.Total = cart_Service.get_cart_total(cart_Service.GetCartID());
            ViewBag.TotalQTY = cart_Service.get_Cart_Items().FindAll(x => x.cart_id == cart_Service.GetCartID()).Sum(q => q.quantity);
            //TempData["Show"] = "There is not enough stock for your request, avaliable stock " + ;
            return View(cart_Service.get_Cart_Items().FindAll(x => x.cart_id == cart_Service.GetCartID()));
        }
        [HttpPost]
        public ActionResult ShoppingCart(List<Cart_Item> items)
        {
            foreach (var i in items)
            {
                cart_Service.updateCart(i.cart_item_id, i.quantity);
                
            }          
            return RedirectToAction("ShoppingCart");
            
        }
        public ActionResult countCartItems()
        {
            int qty = cart_Service.get_Cart_Items().Sum(x => x.quantity);
            return Content(qty.ToString());
        }
        //public ActionResult TextBox(int? Quantity, int? id)
        //{
        //    Cart_Item c = db.Cart_Items.Find(id);
        //    Item p = db.Items.Find(c.item_id);
        //    if (Quantity > c.quantity)
        //    {
        //        c.quantity = c.quantity + (Convert.ToInt16(Quantity) - c.quantity);
        //        if (c.quantity > p.QuantityInStock)
        //        {
        //            TempData["Show"] = "There is not enough stock for your request, avaliable stock " + p.QuantityInStock;
        //            return RedirectToAction("Index");
        //        }
        //        p.QuantityInStock = p.QuantityInStock - c.quantity;
        //        c.price = p.Price * c.quantity;
        //        db.Entry(c).State = EntityState.Modified;
        //        db.Entry(p).State = EntityState.Modified;
        //        db.SaveChanges();
        //    }
        //    else if (Quantity < c.quantity)
        //    {
        //        c.quantity = c.quantity - (c.quantity - Convert.ToInt16(Quantity));
        //        p.QuantityInStock = p.QuantityInStock + c.quantity;
        //        c.price = p.Price * c.quantity;
        //        db.Entry(c).State = EntityState.Modified;
        //        db.Entry(p).State = EntityState.Modified;
        //        db.SaveChanges();
        //    }
        //    return RedirectToAction("ShoppingCart");
        //}
        public ActionResult Checkout(int? Quantity, int? id)
        {
            var I= new Item();
            Item p = db.Items.Find(I.ItemCode);
            var C = new Cart_Item();
            if(C.quantity>I.QuantityInStock)
            {
                TempData["Message"] = "<script>alert('There is not enough stock for your request, avaliable stock ');</script>" + I.QuantityInStock;
                return RedirectToAction("Index");
            }
            if(C.quantity>I.QuantityInStock)
            {
                TempData["Message"] = "<script>alert('There is not enough stock for your request, avaliable stock ');</script>" + I.QuantityInStock;
                return RedirectToAction("Index");
            }


          else  if (cart_Service.get_Cart_Items().Count == 0)
            {
                ViewBag.Err = "Opps... you should have atleat one cart item, please shop a few items";
                return RedirectToAction("Index");
            }
            else
                return RedirectToAction("HowToGetMyOrder");
        }
        [Authorize]
        public ActionResult HowToGetMyOrder()
        {
            return View();
        }
        [HttpPost]
        public ActionResult HowToGetMyOrder(string street_number, string street_name, string City, string State, string ZipCode, string Country)
        {
            Session["street_number"] = street_number;
            Session["street_name"] = street_name;
            Session["City"] = City;
            Session["State"] = State;
            Session["ZipCode"] = ZipCode;
            Session["Country"] = Country;
            return RedirectToAction("PlaceOrder", new { id = "deliver" });
        }
        [Authorize]
        public ActionResult PlaceOrder(string id)
        {
            //Members m = new Members();
            /* Find the details of the customer placing the order*/
            var customer = customer_Service.findCustomer_by_email(HttpContext.User.Identity.Name);
            /* Place the order */
            order_Service.addOrder(customer);
            /* Get the last placed order by the customer */
            var order = order_Service.allOrders()
                .FindAll(x => x.MemberId == customer.MemberId)
                .OrderByDescending(x=>x.date_created)
                .FirstOrDefault();
            /* If the customer requests delivery, save order address */
            if (id == "deliver")
            {
                address_Service.addOrderAddress(new Shipping_Address()
                {
                    Order_ID = order.Order_ID,
                    street_number = Convert.ToInt16(Session["street_number"].ToString()),
                    street_name = Session["street_name"].ToString(),
                    City = Session["City"].ToString(),
                    State = Session["State"].ToString(),
                    ZipCode = Session["ZipCode"].ToString(),
                    Country = Session["Country"].ToString(),

                    Building_Name = "",
                    Floor ="",
                    Contact_Number ="",
                    Comments = "",
                    Address_Type = ""
                });
            }
            /* Migrate cart items to map as order items */
            order_Service.addOrderItems(order,cart_Service.get_Cart_Items());
            /* Empty the cart items */     
            cart_Service.empty_Cart();
            /* Update Order Tracking Report */
            order_Service.addOrderTrackingReport(new Order_Tracking()
            {
                order_ID = order.Order_ID,
                date = DateTime.Now,
                status = "Awaiting Payment",
                Recipient = ""
            });

            //Redirect to payment
            return RedirectToAction("Payment", new { id = order.Order_ID });
        }
        public ActionResult Payment(string id)
        {

            var order = db.Orders.Find(id);

            ViewBag.Order = order;
            ViewBag.Account = customer_Service.findCustomer_by_email(order.members.Email);
            ViewBag.Address = address_Service.allOrderAddreses().Find(x => x.Order_ID == order.Order_ID);
            ViewBag.Items = order_Service.allOrderItems(order.Order_ID);

PowerOfGod.Web/Views/Shopping/HowToGetMyOrder.cshtml
@{
    ViewBag.Title = "How would you like to receive your order?";
    Layout = "~/Views/Shared/_CartLayout.cshtml";
}


<h2 class="title text-center">@ViewBag.Title</h2>
<form method="post">
    <div class="row">
        <div class="board">
            <!-- <h2>Welcome to IGHALO!<sup>™</sup></h2>-->
            <div class="board-inner">
                <ul class="nav nav-tabs" id="myTab">
                    <li class="active" style="text-align:center">
                        <a href="#home" data-toggle="tab" title="Collect at warehouse">
                            <span class="round-tabs">
                                <i class="fa fa-home"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#profile" data-toggle="tab" title="Standard Delivery">
                            <span class="round-tabs">
                                <i class="fa fa-truck"></i>
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="tab-content">
                <div class="tab-pane fade in active" id="home">
                    <h4 class="head text-center">Collect your order at Power Of God Assembles church.</h4>
                    <h4> <i class="fa fa-map-marker"></i>  Umlazi J isidingo Road, Durban, 4031 </h4>
                    <h4> <i class="fa fa-clock-o"></i>  Monday - Friday</h4>
                    <h4> <i class="fa fa-clock-o"></i>  8:30 am - 17:00 pm working hours  Also Sundays During service</h4>
                    <a href="@Url.Action("PlaceOrder","Shopping", new {id = "collect" })" class="btn btn-default"> Continue</a>
                </div>
                <div class="tab-pane fade" id="profile">
                    <h3 class="head text-center">Deliver the order to my address</h3>
                    <div class="input_field">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-map-marker"></i>
                            </div>
                            @*<textarea type="text" class="form-control" id="Physical_Address" ng-model="PropertyModel.Physical_Address" required ng-minlength="3" ng-maxlength="255" style="min-height:100px; resize:none" placeholder="Physical Address"></textarea>*@
                            <div id="locationField">
                                <input id="autocomplete" name="autocomplete" placeholder="Enter your address here" required class="form-control" onFocus="geolocate()" type="text" style="min-width:360px" />
                            </div>
                            <br />
                            <table id="address">
                                <tr>
                                    <td style="color:black;width:70px"><i>Street</i></td>
                                    <td style="min-width:460px" colspan="2">
                                        <input id="street_number" name="street_number" class="field form-control disabled" disabled required="required" style="max-width:60px" />
                                        <input class="field form-control disabled" id="route" disabled name="street_name" required="required" style="max-width:220px" />
                                    </td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td style="color:black;width:70px"><i>City</i></td>
                                    <td class="wideField" colspan="3">
                                        <input class="field  form-control disabled" id="locality" disabled name="City" required="required" />
                                    </td>
                                </tr>
                                <tr>
                                    <td style="color:black;width:70px"><i>State</i></td>
                                    <td style="min-width:460px" colspan="2">
                                        <input class="field form-control disabled" id="administrative_area_level_1" name="State" disabled style="max-width:80px" />
                                        &nbsp;&nbsp;&nbsp;
                                        <i>Zip Code</i>
                                        &nbsp;&nbsp;&nbsp;
                                        <input class="field form-control disabled" id="postal_code" name="ZipCode" disabled required="required" style="max-width:102px" />
                                    </td>
                                </tr>
                                <tr>
                                    <td style="color:black;width:70px"><i>Country</i></td>
                                    <td colspan="3">
                                        <input class="field  form-control disabled" disabled name="Country" id="country" />
                                    </td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td>
                                        <input type="submit" value="Continue" class="btn btn-default" />
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="clearfix"></div>

                </div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
    var $zoho = $zoho || {}; $zoho.salesiq = $zoho.salesiq ||
        { widgetcode: "4133bf52dc5186c72b4359a9ed99f5943ab97e02475cbf6f18bf8d22110d2cbd3df36f2dd283b7efe1698e5454b4a3fa", values: {}, ready: function () { } };
    var d = document; s = d.createElement("script"); s.type = "text/javascript"; s.id = "zsiqscript"; s.defer = true;
    s.src = "https://salesiq.zoho.com/widget"; t = d.getElementsByTagName("script")[0]; t.parentNode.insertBefore(s, t); d.write("<div id='zsiqwidget'></div>");
</script>
<script type="text/javascript">
    $(function () {
        $('a[title]').tooltip();
    });
</script>
<script>
      // This example displays an address form, using the autocomplete feature
      // of the Google Places API to help users fill in the information.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var placeSearch, autocomplete;
      var componentForm = {
        street_number: 'short_name',
        route: 'long_name',
        locality: 'long_name',
        administrative_area_level_1: 'short_name',
        country: 'long_name',
        postal_code: 'short_name'
      };

      function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
        autocomplete = new google.maps.places.Autocomplete(
            @*/** @type {!HTMLInputElement} */*@(document.getElementById('autocomplete')),
            {types: ['geocode']});

        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
        autocomplete.addListener('place_changed', fillInAddress);
      }

      function fillInAddress() {
        // Get the place details from the autocomplete object.
        var place = autocomplete.getPlace();

        for (var component in componentForm) {
            document.getElementById(component).value = '';
            document.getElementById(component).disabled = false;
        }

        // Get each component of the address from the place details
        // and fill the corresponding field on the form.
        for (var i = 0; i < place.address_components.length; i++) {
          var addressType = place.address_components[i].types[0];
          if (componentForm[addressType]) {
            var val = place.address_components[i][componentForm[addressType]];
            document.getElementById(addressType).value = val;
          }
        }
      }

      // Bias the autocomplete object to the user's geographical location,
      // as supplied by the browser's 'navigator.geolocation' object.
      function geolocate() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var geolocation = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            var circle = new google.maps.Circle({
              center: geolocation,
              radius: position.coords.accuracy
            });
            autocomplete.setBounds(circle.getBounds());
          });
        }
      }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAay3hs9-BpmDIMIcmcA-KDGdqZeOEOoV8&libraries=places&callback=initAutocomplete"
        async defer></script>
<script>
    $(function () {
        var input = document.getElementById("autocomplete");
        var autocomplete = new google.maps.places.Autocomplete(input);

        $('#my-modal').modal('show');

    });

</script>

PowerOfGod.Web/Views/Shopping/Index.cshtml
@model IEnumerable<PowerOfGod.Domain.Entity.Shopping.Item>
@{
    ViewBag.Title = "Shopping";
    if (ViewBag.Department != null)
    {
        ViewBag.Title = ViewBag.Department.ToString();
        Layout = "~/Views/Shared/_CartLayout.cshtml";
    }
}
<br />

<h2>All Products</h2>
<hr />
<br />
@*<h2 class="title text-center"> @ViewBag.Title </h2>*@
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm-3">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <div class="productinfo text-center">
                        @if (item.Picture != null)
                        {
                            var base64 = Convert.ToBase64String(inArray: item.Picture);
                            var imgSrc = string.Format(format: "data:image/gif;base64,{0}", arg0: base64);
                            <img src="@imgSrc" width="100" height="149" />
                        }
                        <h3>@Html.DisplayFor(expression: modelItem => item.Price)</h3>
                        <p>
                            <a href="@Url.Action("Details","Items", new { id=item.ItemCode })" rel="tooltip" title="View" style="color:black;">
                                <b>
                                    @Html.DisplayFor(expression: modelItem => item.Name)
                                </b>
                            </a>
                        </p>
                        @if (item.QuantityInStock == 0)
                        {
                            <a href="@Url.Action(actionName: "add_to_cart", controllerName: "Shopping", routeValues: new {id = item.ItemCode})" class="btn disabled btn-default"><i class="fa fa-shopping-cart disabled"></i> Out of stock</a>
                            @*<a href="/Details/Items/@item.ItemCode"><i class="glyphicon glyphicon-zoom-in" aria-hidden="true"></i></a>*@
                            <a href="@Url.Action("Details","Items", new { id=item.ItemCode })" rel="tooltip" title="View" class="btn btn-info btn-simple btn-xs"><i class="fa fa-eye"></i></a>
                        }
                        else
                        {
                            <a href="@Url.Action(actionName: "add_to_cart", controllerName: "Shopping", routeValues: new {id = item.ItemCode})" class="btn btn-default"><i class="fa fa-shopping-cart"></i> Add to cart</a>
                            <a href="@Url.Action("Details","Items", new { id=item.ItemCode })" rel="tooltip" title="View" class="btn btn-info btn-simple btn-xs"><i class="fa fa-eye"></i></a>
                        }
                    </div>
                    @*<div class="col-sm-8 col-md-5 col-sm-offset-2 col-md-offset-0">
                <form class="newsletter-form">
                    <input type="email" placeholder="Enter your email">
                    <button class="nl-send-btn">subscribe</button>
                </form>
            </div>*@
        </div>
    </div>
            <script type="text/javascript">
                var $zoho = $zoho || {}; $zoho.salesiq = $zoho.salesiq ||
                    { widgetcode: "4133bf52dc5186c72b4359a9ed99f5943ab97e02475cbf6f18bf8d22110d2cbd3df36f2dd283b7efe1698e5454b4a3fa", values: {}, ready: function () { } };
                var d = document; s = d.createElement("script"); s.type = "text/javascript"; s.id = "zsiqscript"; s.defer = true;
                s.src = "https://salesiq.zoho.com/widget"; t = d.getElementsByTagName("script")[0]; t.parentNode.insertBefore(s, t); d.write("<div id='zsiqwidget'></div>");
            </script>

                    @*<!-- The Modal -->
        <div class="modal" id="myModal">
            <div class="modal-dialog">
                <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">Modal Heading</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        Modal body..
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    </div>

                </div>
            </div>
        </div>*@










                    @*<div class="product-overlay">
            <div class="overlay-content">
            <h2>@Html.DisplayFor(expression: modelItem => item.Price)</h2>
            <p><a href="@Url.Action("Details","Items", new { id=item.ItemCode })" rel="tooltip" title="View" style="color:black;">
                <b>
                      @Html.DisplayFor(expression: modelItem => item.Name)
                </b>
            </a></p>
           @if (item.QuantityInStock == 0)
        {
            <a href="@Url.Action(actionName: "add_to_cart", controllerName: "Shopping", routeValues: new {id = item.ItemCode})" class="btn disabled btn-default"><i class="fa fa-cart-plus disabled"></i> Out of stock</a>
        }
        else
        {
            <a href="@Url.Action(actionName: "add_to_cart", controllerName: "Shopping", routeValues: new {id = item.ItemCode})" class="btn btn-default"><i class="fa fa-cart-plus"></i> Add to cart</a>
        }
            </div>
        </div>*@
              
                @*<div class="choose">
                        <ul class="nav nav-pills nav-justified">
                            <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                            <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                        </ul>
                    </div>*@
            </div>
       
    }
</div>

@if (ViewBag.Err != null)
{

}

PowerOfGod.Web/Views/Shopping/Payment_Successfull.cshtml
@{
    ViewBag.Title = "Payment_Successfull";
    Layout = "~/Views/Shared/_CartLayout.cshtml";
}

<h2>Payment_Successfull</h2>