PowerOfGod.Web/Controllers/PastorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PowerOfGod.Domain.Context;
using PowerOfGod.Domain.Entity.Booking;

namespace PowerOfGod.Web.Controllers
{
    public class PastorsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Pastors
        public async Task<ActionResult> Index()
        {
            var pastors = db.pastors.Include(p => p.typeOfPastor);
            return View(await pastors.ToListAsync());
        }

        public ActionResult GetPastorTypes()
        {
            return Json(db.TypeOfpastors.ToList(), JsonRequestBehavior.AllowGet);
            //return Json(typeList, JsonRequestBehavior.AllowGet);
        }


        public ActionResult GetPastor(int TypeOfPastorID)
        {
            //var pastor = pastorList.Where(p => p.TypeOfPastorID == PastorID);
            // return Json(pastor, JsonRequestBehavior.AllowGet);
            return Json(db.pastors.ToList().Where(p => p.TypeOfPastorID == TypeOfPastorID), JsonRequestBehavior.AllowGet);
        }
        // GET: Pastors/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pastor pastor = await db.pastors.FindAsync(id);
            if (pastor == null)
            {
                return HttpNotFound();
            }
            return View(pastor);
        }

        // GET: Pastors/Create
        public ActionResult Create()
        {
            ViewBag.TypeOfPastorID = new SelectList(db.TypeOfpastors, "TypeOfPastorID", "Pastortype");
            return View();
        }

        // POST: Pastors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "PastorID,PfirstName,PlastName,BookAmount,Cellnumber,Email,TypeOfPastorID")] Pastor pastor)
        
        {
            if (ModelState.IsValid)
            {

               // upload Picture
                //byte[] data = null;
                //data = new byte[img_upload.ContentLength];
                //img_upload.InputStream.Read(data, 0, img_upload.ContentLength);
                //pastor.Picture= data;

                db.pastors.Add(pastor);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.TypeOfPastorID = new SelectList(db.TypeOfpastors, "TypeOfPastorID", "Pastortype", pastor.TypeOfPastorID);
            return View(pastor);
        }

        // GET: Pastors/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pastor pastor = await db.pastors.FindAsync(id);
            if (pastor == null)
            {
                return HttpNotFound();
            }
            ViewBag.TypeOfPastorID = new SelectList(db.TypeOfpastors, "TypeOfPastorID", "Pastortype", pastor.TypeOfPastorID);
            return View(pastor);
        }

        // POST: Pastors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PastorID,PfirstName,PlastName,BookAmount,Cellnumber,Email,TypeOfPastorID")] Pastor pastor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pastor).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.TypeOfPastorID = new SelectList(db.TypeOfpastors, "TypeOfPastorID", "Pastortype", pastor.TypeOfPastorID);
            return View(pastor);
        }

        // GET: Pastors/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pastor pastor = await db.pastors.FindAsync(id);
            if (pastor == null)
            {
                return HttpNotFound();
            }
            return View(pastor);
        }

        // POST: Pastors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Pastor pastor = await db.pastors.FindAsync(id);
            db.pastors.Remove(pastor);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PowerOfGod.Web/Views/Pastors/Create.cshtml
@model PowerOfGod.Domain.Entity.Booking.Pastor
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutLess.cshtml";
}
<br /><br /><br /><br /><br />
<h2>Enter New Pastor</h2>


@using (Html.BeginForm("Create", "Pastors", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PfirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PfirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PfirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlastName, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="img_upload" id="img_upload" />
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.BookAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cellnumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cellnumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cellnumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeOfPastorID, "Type of Pastor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeOfPastorID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeOfPastorID, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
      
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<br /><br /><br /><br />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")





}

PowerOfGod.Web/Views/Pastors/Delete.cshtml
@model PowerOfGod.Domain.Entity.Booking.Pastor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pastor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.typeOfPastor.Pastortype)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.typeOfPastor.Pastortype)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PfirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PfirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cellnumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cellnumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PowerOfGod.Web/Views/Pastors/Details.cshtml
@model PowerOfGod.Domain.Entity.Booking.Pastor

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pastor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.typeOfPastor.Pastortype)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.typeOfPastor.Pastortype)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PfirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PfirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cellnumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cellnumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PastorID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PowerOfGod.Web/Views/Pastors/Edit.cshtml
@model PowerOfGod.Domain.Entity.Booking.Pastor

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pastor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PastorID)

        <div class="form-group">
            @Html.LabelFor(model => model.PfirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PfirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PfirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cellnumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cellnumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cellnumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeOfPastorID, "TypeOfPastorID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeOfPastorID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeOfPastorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PowerOfGod.Web/Views/Pastors/Index.cshtml
@model IEnumerable<PowerOfGod.Domain.Entity.Booking.Pastor>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUserLess.cshtml";
}
<br /><br /><br /><br /><br />
<h2>Pastor details</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.typeOfPastor.Pastortype)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PfirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlastName)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.BookAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cellnumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.typeOfPastor.Pastortype)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PfirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlastName)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.BookAmount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cellnumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PastorID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PastorID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PastorID })
        </td>*@
    </tr>
}

</table>