PowerOfGod.Web/Controllers/VenueBookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PowerOfGod.Domain.Entity.Booking;
using Microsoft.AspNet.Identity;
using PowerOfGod.Domain.Context;
using PowerOfGod.ViewModel.BookingAproval;
using System.Text;
using PowerOfGod.Domain.Entity.Transactions;

namespace PowerOfGod.Web.Controllers
{
    public class VenueBookingsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: VenueBookings
        public async Task<ActionResult> BookingIndexVenue()
        {
            var venueBooking = db.venueBooking.Include(v => v.Venue).Include(v => v.VenueBookingDescription);
            return View(await venueBooking.ToListAsync());
        }
        public async Task<ActionResult> Index()
        {
            var venueBooking = db.venueBooking.Include(v => v.Venue).Include(v => v.VenueBookingDescription);
            return View(await venueBooking.ToListAsync());
        }

        // GET: VenueBookings/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VenueBooking venueBooking = await db.venueBooking.FindAsync(id);
            if (venueBooking == null)
            {
                return HttpNotFound();
            }
            return View(venueBooking);
        }

        // GET: VenueBookings/Create
        public ActionResult Create()
        {
            ViewBag.VenueID = new SelectList(db.venues, "VenueID", "Venue_Name");
            ViewBag.DescriptionID = new SelectList(db.venueBookingDescription, "DescriptionID", "booking_Description");
            return View();
        }

        // POST: VenueBookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "VenueBookingID,Vstart_date,StartTime,EndTime,Venue_Status,UserId,DescriptionID,VenueID,BookedBy,Email,Venue_Status")] VenueBooking venueBooking)
        {

            UserManager<ApplicationUser> usermanager = new UserManager<ApplicationUser>(new Microsoft.AspNet.Identity.EntityFramework.UserStore<ApplicationUser>(db));

            //Venue venue = new Venue();
            //venue = db.venues.Find(venueBooking.VenueID);
            ////pastorBooking.BookingAmount = pastor.BookAmount;
            //var desc = db.venueBookingDescription.Find(venueBooking.VenueBookingDescription);
            //var transaction = new Transactions()
            //{

            //    //transId = 1,
            //    date = venueBooking.Vstart_date,
            //    // pastorBooking.BookingAmount = pastor.BookAmount,
            //    amount = venue.Price,
            //    transCode = "BOOK102",
            //    description = desc.booking_Description,
            //};
            //db.Transactions.Add(transaction);
            //db.SaveChanges();

            int result = DateTime.Compare(DateTime.Now, venueBooking.Vstart_date);
            DateTime sDate = db.venueBooking.Where(p => p.Vstart_date == venueBooking.Vstart_date).Select(p => p.Vstart_date).FirstOrDefault();



            if (ModelState.IsValid == true && venueBooking.CheckedDate() == true && (venueBooking.Vstart_date == sDate) == false)
            {
                var venue = db.venues.Find(venueBooking.VenueID);
                venueBooking.V_Price = venue.Price;
                venueBooking.Venue_Status = "Waiting for Approval";
                string Amount = venueBooking.V_Price.ToString();
                venueBooking.User = usermanager.FindByEmail(User.Identity.Name);
                venueBooking.BookedBy = venueBooking.User.fullName;
                db.venueBooking.Add(venueBooking);
                await db.SaveChangesAsync();
                return RedirectToAction("Payfast", new { Amount, venueBooking.VenueBookingID, venueBooking.DescriptionID });
            }

            ViewBag.VenueID = new SelectList(db.venues, "VenueID", "Venue_Name", venueBooking.VenueID);
            ViewBag.DescriptionID = new SelectList(db.venueBookingDescription, "DescriptionID", "booking_Description", venueBooking.DescriptionID);
            return View(venueBooking);
        }

        //============================= ApproveBooking =================================
        // GET: PastorBookings/Edit/5
        public ActionResult ApproveVenueBooking(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VenueBooking venueBookings = db.venueBooking.Find(id);
            return View(new ApprovalVenueVM
            {
                VenueBookingID = venueBookings.VenueBookingID,
                //  updateBy = e.updateBy,
                Venue_Status = venueBookings.Venue_Status,
            });
        }
        [HttpPost]
        public ActionResult ApproveVenueBooking(ApprovalVenueVM approveVenue)
        {
            var BookVenue = db.venueBooking.Find(approveVenue.VenueBookingID);

            // BookPastor.updateBy = "Pastor";
            BookVenue.Venue_Status = approveVenue.Venue_Status;
            db.Entry(BookVenue).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        // ========================== ApproveBooking End================================== 

        public async Task<ActionResult> SuccesFullVenueBooking()
        {

            return View();
        }

        //=====================================================Payment========================================

        public ActionResult PayFast(string Amount)
        {
            // Create the order in your DB and get the ID
            string V_Price = Amount;
            string VenueBookingID = new Random().Next(1, 9999).ToString();
            string name = "Booking Ref#" + VenueBookingID;
            string description = "Venue Bookings";

            string site = "";
            string merchant_id = "";
            string merchant_key = "";

            // Check if we are using the test or live system
            string paymentMode = System.Configuration.ConfigurationManager.AppSettings["PaymentMode"];

            if (paymentMode == "test")
            {
                site = "https://sandbox.payfast.co.za/eng/process?";
                merchant_id = "10005631";
                merchant_key = "znbndc034nb6b";
            }
            else
            {
                throw new InvalidOperationException("Cannot process payment if PaymentMode (in web.config) value is unknown.");
            }
            // Build the query string for payment site

            System.Text.StringBuilder str = new StringBuilder();
            str.Append("merchant_id=" + HttpUtility.UrlEncode(merchant_id));
            str.Append("&merchant_key=" + HttpUtility.UrlEncode(merchant_key));
            str.Append("&return_url=" + HttpUtility.UrlEncode(System.Configuration.ConfigurationManager.AppSettings["PF_ReturnURL"]));
            str.Append("&cancel_url=" + HttpUtility.UrlEncode(System.Configuration.ConfigurationManager.AppSettings["PF_CancelURL"]));
            // str.Append("&notify_url=" + HttpUtility.UrlEncode(System.Configuration.ConfigurationManager.AppSettings["PF_NotifyURL"]));
            str.Append("&m_payment_id=" + HttpUtility.UrlEncode(VenueBookingID));
            str.Append("&amount=" + HttpUtility.UrlEncode(V_Price));
            str.Append("&item_name=" + HttpUtility.UrlEncode(name));
            str.Append("&item_description=" + HttpUtility.UrlEncode(description));

            // Redirect to PayFast
            Response.Redirect(site + str.ToString());

            return View();
        }

        public ActionResult Success(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VenueBooking venueBooking = db.venueBooking.Find(id);
            if (venueBooking == null)
            {
                return HttpNotFound();
            }
            return View(venueBooking);

        }
        public ActionResult Acknowledgement(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VenueBooking venueBooking = db.venueBooking.Find(id);
            if (venueBooking == null)
            {
                return HttpNotFound();
            }
            return View(venueBooking);
        }

        //======================================== Payment ================================================================



        // GET: VenueBookings/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VenueBooking venueBooking = await db.venueBooking.FindAsync(id);
            if (venueBooking == null)
            {
                return HttpNotFound();
            }
            ViewBag.VenueID = new SelectList(db.venues, "VenueID", "Venue_Name", venueBooking.VenueID);
            ViewBag.DescriptionID = new SelectList(db.venueBookingDescription, "DescriptionID", "booking_Description", venueBooking.DescriptionID);
            return View(venueBooking);
        }

        // POST: VenueBookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 

PowerOfGod.Web/Views/VenueBookings/Acknowledgement.cshtml
@model PowerOfGod.Domain.Entity.Booking.VenueBooking


@{
    ViewBag.Title = "Acknowledgement";
}

<h2>Acknowledgement</h2>
<p>Your Name   :  @Html.DisplayFor(Name => Name.UserId)</p>
<p>Booking Date  :  @Html.DisplayFor(Date => Date.Start_date)</p>
@*Your Name*@
@*Your Address
    Your City, State, Zip Code
    Your Phone Number
    Your Email*@
@*Date*@


<p>Title:Donation Acknowledgement </p>
<p>Company: Power Of God Assembles</p>
<p>Address:Isding Rd , Umalzi J, </p>
<p>City:Umalzi State:KZN Zip Code:408</p>
<p></p>
<p></p>

<p>Dear @Html.DisplayFor(Name => Name.UserId)</p>;
<p>On behalf of Power Of God Assembles, we would like to thank you for your generous donation of R @Html.DisplayFor(Amount => Amount.BookingAmount), which we received on @Html.DisplayFor(Date => Date.Start_date). Your support will go a long way in helping us achieve our goals of @Html.DisplayFor(Description => Description.ReasonID).</p>
<p>As you know, Power Of God Assembles is a non-profit organization and is subject to tax exemption. This is to certify that no goods and services were provided in exchange for this donation and will serve as documentation for your tax records. Please keep this letter as your receipt for the donation made to Power Of God Assembles.</p>
<p>Thank you very much for your continued support of our program.</p>
<p></p>
<p></p>
<p>Sincerely,</p>
<p>Your name and signature</p>
<p>Position</p>
<p>Power Of God Assembles</p>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

PowerOfGod.Web/Views/VenueBookings/ApproveVenueBooking.cshtml
@model PowerOfGod.ViewModel.BookingAproval.ApprovalVenueVM
@if (User.IsInRole("SupperAdmin"))
{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_supadmin.cshtml";
}
else if (User.IsInRole("Administrator"))
{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_admin.cshtml";
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">

<div style="margin-bottom:10%;"></div>

<div style="margin-bottom:10%;"></div>
<h3 class="page-header"><i class="fa fa-list-alt"></i>Booking Approvel</h3>
<ol class="breadcrumb">
    <li><i class="fa fa-home"></i><a href="#">Home</a></li>
    <li><i class="fa fa-desktop"></i>Approvel</li>
</ol>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VenueBookingID)
        @*<div class="form-group">
                @Html.LabelFor(model => model.LeaveID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LeaveID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LeaveID, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="form-group">
            @Html.LabelFor(model => model.Venue_Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.Venue_Status, "Approved") @Html.Label("Approved")
                @Html.RadioButtonFor(model => model.Venue_Status, "Rejected") @Html.Label("Rejected")
                @Html.ValidationMessageFor(model => model.Venue_Status, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.updateBy, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.updateBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.updateBy, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
</div>

PowerOfGod.Web/Views/VenueBookings/BookingIndexVenue.cshtml
@model IEnumerable<PowerOfGod.Domain.Entity.Booking.VenueBooking>

@{
    ViewBag.Title = "BookingIndexVenue";
    Layout = "~/Views/Shared/_LayoutUserLess.cshtml";
}
<br /><br /><br /><br /><br />
<h2>Booking Details</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Venue.Venue_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VenueBookingDescription.booking_Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vstart_date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.V_Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Venue_Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BookedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberInUse)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Venue.Venue_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VenueBookingDescription.booking_Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Vstart_date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.V_Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Venue_Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BookedBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberInUse)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.VenueBookingID }) |
            @Html.ActionLink("Details", "Details", new { id=item.VenueBookingID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.VenueBookingID })
        </td>*@
    </tr>
}

</table>

PowerOfGod.Web/Views/VenueBookings/Create.cshtml
@model PowerOfGod.Domain.Entity.Booking.VenueBooking

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutUserLess.cshtml";
}
<br /><br /><br /><br /><br />
<h2>Venue Booking</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <br /><br />
        <br />
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Vstart_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vstart_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vstart_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>


        @*<div class="form-group">
            @Html.LabelFor(model => model.ReserveVenue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ReserveVenue)
                    @Html.ValidationMessageFor(model => model.ReserveVenue, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

        
        <div class="form-group">
            @Html.LabelFor(model => model.DescriptionID, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DescriptionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DescriptionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VenueID, "Venue", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VenueID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VenueID, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<br /><br /><br />

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
@section Scripts {
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

    <script type="text/javascript">

        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0",
                minDate: new Date(),
                singleMonth: true,
                beforeShowDay: function (t) {
                    var valid = t.getDay() !== 0; //disable sunday
                    var _class = '';
                    // var _tooltip = valid ? '' : 'weekends are disabled';
                    return [valid, _class];

                }
            });

        });
    </script>
}

PowerOfGod.Web/Views/VenueBookings/Delete.cshtml
@model PowerOfGod.Domain.Entity.Booking.VenueBooking

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VenueBooking</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Venue.Venue_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Venue.Venue_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VenueBookingDescription.booking_Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VenueBookingDescription.booking_Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vstart_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vstart_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Venue_Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Venue_Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReserveVenue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReserveVenue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberInUse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberInUse)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PowerOfGod.Web/Views/VenueBookings/Details.cshtml
@model PowerOfGod.Domain.Entity.Booking.VenueBooking

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>VenueBooking</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Venue.Venue_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Venue.Venue_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VenueBookingDescription.booking_Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VenueBookingDescription.booking_Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vstart_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vstart_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Venue_Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Venue_Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReserveVenue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReserveVenue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberInUse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberInUse)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.VenueBookingID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PowerOfGod.Web/Views/VenueBookings/PayFast.cshtml
@model PowerOfGod.Domain.Entity.Booking.VenueBooking

@{
    ViewBag.Title = "PayFast";
}

<h2>PayFast</h2>*@*@*@

<script src="~/Scripts/jquery-3.1.1.js"></script>
<div class="w3ls_banner_section">
    <div class="container">
        @using (Html.BeginForm("PayFast", "payment", FormMethod.Get))
        {
            <div class="row">
                <div class="col-lg-4"></div>
                <div class="col-lg-4">
                    <p>
                        <div class="input-group">
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-success">Make Payment </button>
                            </div>
                            @Html.TextBox("Amount", null, new { @class = "form-control", @required = "required", @type = "number",@placeholder = "Enter amount.."})
                        </div>


                    </p>
                </div>
                <div class="col-lg-4"></div>
            </div>

        }

PowerOfGod.Web/Views/VenueBookings/SuccesFullVenueBooking.cshtml
@model PowerOfGod.Domain.Entity.Booking.VenueBooking
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">
<div style="margin-bottom:10%;"></div>

<div style="margin-bottom:10%;"></div>
<h3 class="page-header"><i class="fa fa-list-alt"></i>Your Booking Been Successful Please see booking On My Venue Bookings</h3>
<div>
    <li>@Html.ActionLink("Make payment", "Payfast", "VenueBookings")</li>
    <li>@Html.ActionLink("My Venue bookings", "VenenueBookingAll", "VenueBookingVMs")</li>
</div>

PowerOfGod.Web/Views/VenueBookings/Success.cshtml
@model PowerOfGod.Domain.Entity.Booking.VenueBooking

@{
    ViewBag.Title = "Success";
}

<h2>Success</h2>

<div>
    @*<h4>Donation</h4>*@
    <img src="~/images/donationHeader.png" />
    <hr />
    <p>Booking Date   :  @Html.DisplayFor(Date => Date.date)</p>
    <p>By              :  @Html.DisplayFor(Name => Name.name)</p>
    <p>Amount Donated R:  @Html.DisplayFor(Amount => Amount.amount)</p>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>